#! /bin/bash

echo "Running test script 1"

PWD="$(pwd)"
WORK_DIR="${1}"
WORK_DIR_REPO="${2}"
SRC_MANIFEST_PATH="${3}"
DST_MANIFEST_PATH="${4}"
SRC_MANIFEST_FILE_PATH="${5}"
DST_MANIFEST_FILE_PATH="${6}"
SRC_REPO_URL="${7}"
DST_REPO_URL="${8}"


SRC_NAME="${11}"
SRC_PATH="${12}"
SRC_REVISION="${13}"
SRC_REMOTE="${14}"
SRC_GROUPS="${15}"
SRC_UPSTREAM="${16}"
SRC_FULL_PATH="${17}"
SRC_FILE_PATH="${18}"
SRC_REMOTE_PATH="${19}"

DST_NAME="${31}"
DST_PATH="${32}"
DST_REVISION="${33}"
DST_REMOTE="${34}"
DST_GROUPS="${35}"
DST_UPSTREAM="${36}"
DST_FULL_PATH="${37}"
DST_FILE_PATH="${38}"
DST_REMOTE_PATH="${39}"

echo ""
echo "PWD                       = ${PWD}"
echo "WORK_DIR                  = ${WORK_DIR}"
echo "WORK_DIR_REPO             = ${WORK_DIR_REPO}"
echo ""
echo "SRC_MANIFEST_PATH         = ${SRC_MANIFEST_PATH}"
echo "DST_MANIFEST_PATH         = ${DST_MANIFEST_PATH}"
echo "SRC_MANIFEST_FILE_PATH    = ${SRC_MANIFEST_FILE_PATH}"
echo "DST_MANIFEST_FILE_PATH    = ${DST_MANIFEST_FILE_PATH}"
echo ""
echo "SRC_REPO_URL              = ${SRC_REPO_URL}"
echo "DST_REPO_URL              = ${DST_REPO_URL}"
echo ""
echo "SRC_NAME                  = ${SRC_NAME}"
echo "SRC_PATH                  = ${SRC_PATH}"
echo "SRC_REVISION              = ${SRC_REVISION}"
echo "SRC_REMOTE                = ${SRC_REMOTE}"
echo "SRC_GROUPS                = ${SRC_GROUPS}"
echo "SRC_UPSTREAM              = ${SRC_UPSTREAM}"
echo "SRC_FULL_PATH             = ${SRC_FULL_PATH}"
echo "SRC_FILE_PATH             = ${SRC_FILE_PATH}"
echo "SRC_REMOTE_PATH           = ${SRC_REMOTE_PATH}"
echo ""
echo "DST_NAME                  = ${DST_NAME}"
echo "DST_PATH                  = ${DST_PATH}"
echo "DST_REVISION              = ${DST_REVISION}"
echo "DST_REMOTE                = ${DST_REMOTE}"
echo "DST_GROUPS                = ${DST_GROUPS}"
echo "DST_UPSTREAM              = ${DST_UPSTREAM}"
echo "DST_FULL_PATH             = ${DST_FULL_PATH}"
echo "DST_FILE_PATH             = ${DST_FILE_PATH}"
echo "DST_REMOTE_PATH           = ${DST_REMOTE_PATH}"